name: main build

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "build_0_7_0"
            viash_version: "0.7.0"
          - name: "build_0_7_1"
            viash_version: "0.7.1"
          - name: "build_0_7_2"
            viash_version: "0.7.2"
          - name: "build_0_7_3"
            viash_version: "0.7.3"
          - name: "build_0_7_4"
            viash_version: "0.7.4"
          - name: "build_0_7_5"
            viash_version: "0.7.5"
          - name: "build_0_8_0"
            viash_version: "0.8.0"
          - name: "build_0_8_1"
            viash_version: "0.8.1"
          - name: "build_0_8_2"
            viash_version: "0.8.2"
          - name: "build_0_8_3"
            viash_version: "0.8.3"
          - name: "build_0_8_4"
            viash_version: "0.8.4"
          - name: "build_0_8_5"
            viash_version: "0.8.5"
          - name: "build_0_8_6"
            viash_version: "0.8.6"
          - name: "build_0_9_0_RC1"
            viash_version: "0.9.0-RC1"
          - name: "build_0_9_0_RC2"
            viash_version: "0.9.0-RC2"
          - name: "build_0_9_0_RC4"
            viash_version: "0.9.0-RC4"
          - name: "build_0_9_0_RC6"
            viash_version: "0.9.0-RC6"

    steps:
      - uses: actions/checkout@v4
    
      - uses: actions/cache@v4
        with:
          path: ~/.local/bin/viash
          key: viash_${{ matrix.name }}
  
      - uses: viash-io/viash-actions/setup@v6
        if: ${{ hashFiles('~/.local/bin/viash') == '' }}
        with:
          version: ${{ matrix.viash_version }}
      
      - name: Specify package version
        run: |
          if [[ ${{ matrix.name }} == build_0_9_* ]]; then
            cp _viash_0.9.yaml _viash.yaml
            echo "version: ${{matrix.name}}" >> _viash.yaml
          else
            sed -i "s/'dev'/'${{ matrix.name }}'/g" _viash.yaml
          fi

      - name: Remove target folder from .gitignore
        run: |
          # allow publishing the target folder
          sed -i '/^target.*/d' .gitignore

      - uses: viash-io/viash-actions/ns-build@v6
        with:
          parallel: true
          setup: build

      - name: Deploy to target branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: '${{ matrix.name }}'
          
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GTHB_USER }}
          password: ${{ secrets.GTHB_PAT }}

      - name: Push container
        run: |
          if [[ ${{ matrix.name }} == build_0_9_* ]]; then
            viash ns build --setup push --parallel --engine docker
          else
            viash ns build --setup push --parallel --platform docker
          fi
